// Shared StyleSheet for the teacher content screen + its child components.
// Kept verbatim from app/(teacher)/content.tsx so visual output is identical.
import { StyleSheet } from 'react-native';
import { Colors } from '../../../constants/colors';
import { tokens } from '../../../constants/designTokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  tabBar: {
    flexDirection: 'row',
    alignItems: 'center', // RNW: prevents flex children (chips) from stretching vertically;
                          // without this the active chip's LinearGradient fills the full
                          // ScrollView height and a tall navy/white column overlays the list.
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    backgroundColor: tokens.color.surface,
    borderBottomWidth: 1,
    borderBottomColor: tokens.color.border,
  },
  listContent: {
    padding: 16,
    gap: 10,
  },
  card: {
    backgroundColor: tokens.color.surface,
    borderRadius: tokens.radius.xl,
    padding: 16,
    borderWidth: 1,
    borderColor: tokens.color.border,
    ...tokens.shadow.sm,
  },
  addBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 6,
  },
  addBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  emptyText: {
    fontSize: 13,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingVertical: 30,
  },
  // Video
  videoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  videoThumb: {
    width: 56,
    height: 42,
    borderRadius: tokens.radius.sm,
    backgroundColor: tokens.color.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoInfo: {
    flex: 1,
  },
  videoTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'right',
  },
  videoDate: {
    fontSize: 10,
    color: Colors.textMuted,
    textAlign: 'right',
    marginTop: 2,
  },
  deleteBtn: {
    padding: 8,
  },
  // Exam
  examRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  examTile: {
    width: 44,
    height: 44,
    borderRadius: tokens.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  examTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'right',
  },
  examMeta: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
  },
  examMetaText: {
    fontSize: 10,
    color: Colors.textMuted,
  },
  statusBadge: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  // Gallery
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  galleryCard: {
    backgroundColor: tokens.color.surface,
    borderRadius: tokens.radius.lg,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tokens.color.border,
  },
  galleryThumb: {
    width: 60,
    height: 60,
    borderRadius: tokens.radius.md,
    backgroundColor: tokens.color.surface2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  galleryName: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.text,
    textAlign: 'center',
  },
  // Materials
  materialRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  materialTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'right',
  },
  materialPrice: {
    fontSize: 12,
    color: Colors.success,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: 2,
  },
  buyersBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.color.brand100,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  buyersText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.primary,
  },
  materialActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 4,
    marginTop: -4,
    marginBottom: 8,
    paddingHorizontal: 8,
  },
  // Modal
  sheetBody: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.text,
  },
  input: {
    backgroundColor: tokens.color.surface2,
    borderWidth: 1,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: '600',
    color: tokens.color.text,
    marginBottom: 10,
  },
  textArea: {
    minHeight: 70,
    paddingTop: 10,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.text,
    textAlign: 'right',
    marginBottom: 6,
  },
  classChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: tokens.radius.sm,
    backgroundColor: tokens.color.surface2,
    marginRight: 6,
  },
  classChipActive: {
    backgroundColor: Colors.primary,
  },
  classChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.textMuted,
  },
  classChipTextActive: {
    color: '#fff',
  },
  filePickerBtn: {
    borderWidth: 2,
    borderColor: Colors.border,
    borderStyle: 'dashed',
    borderRadius: 14,
    padding: 24,
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  filePickerText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.textMuted,
  },
  primaryBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 6,
  },
  primaryBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  // Exam questions
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  radioBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioBtnActive: {
    borderColor: Colors.success,
  },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.success,
  },
  tfRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  tfBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: tokens.radius.sm,
    backgroundColor: tokens.color.surface2,
    alignItems: 'center',
  },
  tfBtnActive: {
    backgroundColor: Colors.primary,
  },
  tfBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.textMuted,
  },
  tfBtnTextActive: {
    color: '#fff',
  },
  questionPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: tokens.color.surface2,
    borderRadius: tokens.radius.sm,
    padding: 10,
    marginBottom: 6,
  },
  questionPreviewText: {
    flex: 1,
    fontSize: 12,
    color: Colors.text,
    fontWeight: '600',
    textAlign: 'right',
    marginLeft: 8,
  },
  stepBtnRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  stepBtn: {
    flex: 1,
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  reviewCard: {
    backgroundColor: tokens.color.surface2,
    borderRadius: tokens.radius.lg,
    padding: 16,
    gap: 6,
  },
  reviewLabel: {
    fontSize: 11,
    color: Colors.textMuted,
    fontWeight: '600',
    textAlign: 'right',
  },
  reviewValue: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'right',
    marginBottom: 4,
  },
  examActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: 10,
  },
  examActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  examActionText: {
    fontSize: 11,
    fontWeight: '700',
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    marginBottom: 10,
  },
  toggleLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.text,
  },
  videoCard: {
    backgroundColor: tokens.color.surface,
    borderRadius: tokens.radius.lg,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: tokens.color.border,
  },
});
